# Generated by Django 4.0.4 on 2022-06-24 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteCurso',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('curso', models.CharField(max_length=60)),
                ('monto_solicitado', models.IntegerField()),
                ('monto_depositado', models.IntegerField()),
                ('monto_faltaltante', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'db_reporteCurso',
            },
        ),
        migrations.CreateModel(
            name='Seguro',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(max_length=200)),
                ('precio', models.IntegerField()),
            ],
            options={
                'db_table': 'db_Seguro',
            },
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'db_tipo_producto',
            },
        ),
        migrations.CreateModel(
            name='RegistroViaje',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('clienteCorreo', models.CharField(max_length=30)),
                ('destinoCorreo', models.CharField(max_length=30)),
                ('fechaViaje', models.CharField(max_length=30)),
                ('nAlumnos', models.IntegerField()),
                ('tipoActividad', models.CharField(max_length=30)),
                ('datoRelevante', models.CharField(max_length=30)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tiposervicio')),
            ],
            options={
                'db_table': 'db_registro_viaje',
            },
        ),
    ]
