# Generated by Django 4.0.4 on 2022-06-21 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteCurso',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('curso', models.CharField(max_length=60)),
                ('monto_solicitado', models.IntegerField()),
                ('monto_depositado', models.IntegerField()),
                ('monto_faltaltante', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'db_reporteCurso',
            },
        ),
    ]
