# Generated by Django 4.0.4 on 2022-07-09 22:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratocurso',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='registroviaje',
            name='fechaViaje',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
