from django.urls import path
from .views import *

urlpatterns = [
    path('registro/', registro, name='registro'),
    path('login/', login, name='login'),
    path('base/', base, name='base'),
    path('', cliente, name='cliente'),
    path('contrato/', contrato, name='contrato'),
    path('deposito/', deposito, name='deposito'),
    path('estado/', estado, name='estado'),
    path('monto/', monto, name='monto'),
    path('perfil/', perfil, name='perfil'),
    path('reporte/', reporte, name='reporte'),
    path('contratoCliente/', contratoCliente, name='contratoCliente'),
    path('contratoSeguro/', contratoSeguro, name='contratoSeguro'),
    path('meta/', meta, name='meta'),
    path('publicaciones/', publicaciones, name='publicaciones'),
    path('servicioContratado/', servicioContratado, name='servicioContratado'),
    path('serviciosAdicionales/', serviciosAdicionales, name='serviciosAdicionales'),
    path('registroViaje/', registroViaje, name='registroViaje'),
    path('seguro/', seguro, name='seguro'),
    path('listarSeguro/', listarSeguro, name='listaSeguro'),
    path('agregarSeguro/', agregarSeguro, name='agregarSeguro'),
    path('modificarSeguro/<codigo>', modificarSeguro, name='modificarSeguro'),
    path('eliminarSeguro/<codigo>', eliminarSeguro, name='eliminarSeguro'),
    path('crearReporte/', crearReporte, name='crearReporte'),
    path('listaReporte/', listaReporte, name='listaReporte'),
    path('modificarReporte/<codigo>/', modificaReporte, name='modificarReporte'),
    path('eliminaReporte/<codigo>/', eliminaReporte, name='eliminaReporte'),
]